#pragma once

#include "hresult.h"
#include "guid.h"

#include <cstdint>

namespace ziran
{
	// job report type used in database and in IReporter iface
	enum class NJob_Report_Type : uint32_t
	{
		Info,		// db value 'info'
		Warning,	// db value 'warning'
		Error,		// db value 'error'
	};

	/*
	 * Interface for job message reporting
	 */
	class IReporter
	{
		public:
			virtual ~IReporter() = default;

			// reports a message to a given job; may specify identifier to further distinguish the outputs
			virtual HRESULT Report(NJob_Report_Type type, const char* str, const char* identifier = nullptr, const char* extendedValue = nullptr) = 0;
	};

	/*
	 * Environment interface
	 */
	class IEnvironment
	{
		public:
			virtual ~IEnvironment() = default;

			// retrieves a string from the environment (global configuration)
			virtual HRESULT Get_String(const char* key, const char** const target, const char* default_value = nullptr) const = 0;
			// retrieves an input string from the database (cached in environment) (global configuration)
			virtual HRESULT Get_Input(const char* key, const char** const target) const = 0;

			// retrieves a state string - this is generated by a previous pipeline item
			virtual HRESULT Get_State_String(const char* key, const char** const target) const = 0;
			// sets a state string
			virtual HRESULT Set_State_String(const char* key, const char* value) = 0;
	};

	// descriptor of Ziran plugin
	struct TPlugin_Descriptor
	{
		GUID id;
		const char* name;
	};

	// usual signature: extern "C" HRESULT do_get_plugin_descriptors(ziran::TPlugin_Descriptor** begin, ziran::TPlugin_Descriptor** end)
	using TDo_Get_Plugin_Descriptors = HRESULT(*)(ziran::TPlugin_Descriptor**, ziran::TPlugin_Descriptor**);

	// usual signature: extern "C" HRESULT do_run_plugin(const GUID* id, const char* base_directory, const char** parameter_names, const char** parameter_values, const size_t parameters_count, ziran::IReporter* reporter)
	using TDo_Run_Plugin = HRESULT(*)(const GUID*, const char*, const char**, const char**, const size_t, IReporter*, IEnvironment*);


}
